version: "3.8"

services:
  # api
  api_user:
    build:
      context: ./services
      dockerfile: Dockerfile.api
    image: wisrovi/wyoloservice_api:v1.1.0
    restart: always
    ports:
      - "23450:8000"
    volumes:
      - /media/training/Train_service_an/config_versions:/config_versions
      - /media/training/Train_service_an/api_database:/database
    networks:
      - nfs_network

  # environment
  redis:
    image: redis:latest
    restart: always
    ports:
      - "23438:6379"
    networks:
      - nfs_network

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=redis
      - HTTP_PASSWORD=wyoloservice
    restart: always
    ports:
      - "23439:8081"
    depends_on:
      - redis
    networks:
      - nfs_network


  mlflow-minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    restart: always
    environment:
      - MINIO_ROOT_USER=mlflow
      - MINIO_ROOT_PASSWORD=wyoloservice
    ports:
      - "23444:9000"
      - "23442:9001" # web admin
    volumes:
      - /media/training/Train_service_an/mlflow_minio:/data
    networks:
      - nfs_network

  mlflow:
    build: 
      context: ./enviroment
      dockerfile: Dockerfile.mlflow
    image: wisrovi/wyoloservice:mlflow
    restart: always
    environment:
      # db
      - MLFLOW_BACKEND_STORE_URI=postgresql+psycopg2://postgres:postgres@postgres:5432/wyoloservice # Conexión a PostgreSQL
      # minio
      - MLFLOW_S3_ENDPOINT_URL=http://mlflow-minio:9000 # URL del servidor MinIO
      - AWS_ACCESS_KEY_ID=mlflow # Credenciales de MinIO
      - AWS_SECRET_ACCESS_KEY=wyoloservice # Credenciales de MinIO
      #mlflow
      - MLFLOW_TRACKING_URI=http://mlflow:5000 # URI de seguimiento de MLflow
      - MLFLOW_ARTIFACT_URI=s3://mlflow-artifacts/ # Bucket en MinIO donde se almacenarán los artefactos
    command:
      [
        "mlflow",
        "server",
        "--host",
        "0.0.0.0",
        "--port",
        "5000",
        "--backend-store-uri",
        "postgresql+psycopg2://postgres:postgres@postgres:5432/wyoloservice",
        "--default-artifact-root",
        "s3://mlflow-artifacts/",
      ]
    ports:
      - "23435:5000"
    networks:
      - nfs_network

  postgres:
    image: postgres:13.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=wyoloservice
    volumes:
      - /media/training/Train_service_an/postgres:/var/lib/postgresql/data
    ports:
      - "23436:5432"
    restart: always
    networks:
      - nfs_network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "23437:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: wisrovi.rodriguez@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 12345678
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - nfs_network

    # General:
    #     name: postgres
    # conection:
    #     host name/address: postgres
    #     port: 5432
    #     username: postgres
    #     password: postgres


networks:
  nfs_network:
    external: true

volumes:
  pgadmin-data:

# Para crear la red y el servidor NFS
# docker network create --subnet=28.10.4.0/24 --gateway=28.10.4.1 --driver=bridge nfs_network

# para el NFS, ver datos
# sudo apt install nfs-client -y
# sudo mkdir -p /mnt/wyoloservice/datasets
# sudo mount -v -o vers=4,loud <host-ip>:/ /mnt/wyoloservice/datasets

# para samba:
# smb://<host-ip>/shared

# Instrucciones de uso:
# 1. Crear un archivo .env con las variables de entorno necesarias.
# 2. Ejecutar `docker-compose up -d` para iniciar todos los servicios.
# 3. Acceder a los servicios:
#    - Samba: \\localhost\shared (Windows) o smb://localhost/shared (Linux/Mac)
#    - NFS: montado en /mnt/wyoloservice/datasets
#    - MLflow: http://localhost:5000
#    - MinIO Console: http://localhost:9006
#    - PgAdmin: http://localhost:1717
#    - API: http://localhost:8000
