version: "3.8"

# Define reusable GPU resource constraints
x-resources: &resources_gpu
  # la shm_size es calculada de acuerdo al 80% de la memoria RAM como maximo
  # es importante que el ordenador a entrenar tenga al menos lo mismo de swap que de RAM
  shm_size: "24g"
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "3"
  environment:
    - NVIDIA_VISIBLE_DEVICES=0
    - NVIDIA_DRIVER_CAPABILITIES=compute,utility
  deploy:
    resources:
      limits:
        cpus: "7.0"
        memory: 24g
      reservations:
        # cpus: "1.0"
        # memory: 2048M
        # memory_swap: 500M
        devices:
          - driver: nvidia
            device_ids: ["0"]
            capabilities: [gpu]

services:
  worker:
    <<: *resources_gpu
    build:
      context: ./services
      dockerfile: Dockerfile.worker
    image: wisrovi/wyoloservice_worker:v1.0.8
    container_name: worker_demo
    env_file:
      - control_host.env
      - user.env
    # restart: always
    command: tail -f /dev/null
    privileged: true
    volumes:
      - ./demo:/demo
      - ./services/worker/:/app/worker/
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    labels:
      - "autoheal=true"
      - "com.centurylinklabs.watchtower.enable=true" # Habilita Watchtower para este contenedor
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 20s
      timeout: 2s
      retries: 1
      start_period: 20s


# Para crear la red y el servidor NFS
# docker network create --subnet=28.10.4.0/24 --gateway=28.10.4.1 --driver=bridge nfs_network

# para el NFS, ver datos
# sudo apt install nfs-client -y
# sudo mkdir -p /media/training/Train_service_an/datasets
# sudo mount -v -o vers=4,loud <host-ip>:/ /mnt/train_service_datasets

# para samba:
# smb://<host-ip>/shared

# Instrucciones de uso:
# 1. Crear un archivo .env con las variables de entorno necesarias.
# 2. Ejecutar `docker-compose up -d` para iniciar todos los servicios.
# 3. Acceder a los servicios:
#    - Samba: \\localhost\shared (Windows) o smb://localhost/shared (Linux/Mac)
#    - NFS: montado en /mnt/wyoloservice/datasets
#    - MLflow: http://localhost:5000
#    - MinIO Console: http://localhost:9006
#    - PgAdmin: http://localhost:1717
#    - API: http://localhost:8000
