mlflow:
  MLFLOW_TRACKING_URI: http://mlflow:5000

minio:
  MINIO_ENDPOINT: http://minio:9000
  MINIO_ID: minio
  MINIO_SECRET_KEY: minio123
  MINIO_BUCKET: models

redis:
  REDIS_HOST: redis
  REDIS_PORT: 6379
  REDIS_DB: 0
  REDIS_PASSWORD: ""

default:
  timeout: 60
  max_retries: 3
  retry_delay: 1
  threshold: 0.35

  override hydra/sweeper: optuna


model: yolov8n.pt

train:
  batch: -1
  epochs: 1

sweeper:
  max_t: 100
  grace_period: 5
  max_concurrent: 1
  
