defaults:
  - override hydra/sweeper: optuna
experiment_name: "person.v2i"
content: "Este es un experimento de clasificación de imágenes."
model: "yolov8n.pt"
type: "yolo"
train:
  batch: 32
  data: /datasets/person.v2i.yolov8/data.yaml
  epochs: 10
  imgsz: 640
val:
  #iou: 0.6
  #batch: 32
  conf: 0.01
test:
  conf: 0.01
sweeper:
  version: 1.0
  direction: maximize
  study_name: "yolo_hyperparam_search"
  storage: null
  sampler: "TPESampler"
  n_trials: 3
  params:
    train:
      epochs: ["range", 1, 13, 4]
      # batch: [ "choice", 4, 6, 8 ]
      imgsz: ["choice", 416, 640]
      lr0: ["loguniform", 1e-5, 1e-2]
extras:
  gpu:
    id: 0
    limit: 0.95
