version: "3.8"

services:
  openssl:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: wisrovi/wyoloservice_openssl:latest
    volumes:
      - ./nginx/certs/www.wyoloservice.com:/data
    environment:
      - DOMAIN_NAME=www.wyoloservice.com
    command: >
      openssl req -x509 -nodes -days 825 -newkey rsa:4096 
      -keyout /data/privkey.pem 
      -out /data/fullchain.pem 
      -config /conf/openssl_wisrovi.cnf 
      -extensions v3_req

  nginx-proxy:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/certs:/etc/nginx/certs  # Directorio donde están los certificados SSL
      # - ./nginx/vhost.d:/etc/nginx/vhost.d
      # - ./nginx/html:/usr/share/nginx/html
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf  # Configuración personalizada de Nginx
    networks:
      - nfs_network

networks:
  nfs_network:
    external: true
