version: "3.8"

services:
  dataset_filebrowser:
    image: hurlenko/filebrowser
    privileged: true
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    volumes:
      - ${FOLDER_SHARED}/wyoloservice_data/datasets:/data
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      # - FB_PASSWORD=wyoloservice
      # - FB_USERNAME=wisrovi
      - FB_BASEURL=/datasets
      - VIRTUAL_HOST=wisrovi.com
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=wisrovi.com
      - LETSENCRYPT_EMAIL=wisrovi.rodriguez@gmail.com
    restart: always
    # ports:
    #   - "23443:8080"
    networks:
      - nfs_network
    env_file:
      - control_host.env

  combined_samba:
    image: dperson/samba
    ports:
      - "23449:445/tcp" # Puerto único para el servicio combinado
    restart: always
    env_file:
      - control_host.env
    volumes:
      - ${FOLDER_SHARED}/wyoloservice_data/datasets:/data/datasets
      - ${FOLDER_SHARED}/wyoloservice_data/config_versions:/data/config_versions
      - ${FOLDER_SHARED}/wyoloservice_data/api_database:/data/api_database
    command: >
      -u "${CIFS_USER};${CIFS_PASS}"
      -s "datasets;/data/datasets;yes;no;yes;all"
      -s "config_versions;/data/config_versions;yes;no;yes;all"
      -s "api_database;/data/api_database;yes;no;yes;all"
    networks:
      - nfs_network

  dataset_samba:
    image: dperson/samba
    ports:
      - "23445:445/tcp"
    restart: always
    volumes:
      - ${FOLDER_SHARED}/wyoloservice_data/datasets:/data
    environment:
      - TZ=Europe/Madrid
      - USERID=1000
      - GROUPID=1000
      - SAMBA_USERS=wisrovi;wyoloservice
    command: >
      -u "wisrovi;wyoloservice" -s "shared;/data;yes;no;yes;all"
    networks:
      - nfs_network
    env_file:
      - control_host.env

  config_samba:
    image: dperson/samba
    restart: always
    volumes:
      - ${FOLDER_SHARED}/wyoloservice_data/config_versions:/data
    environment:
      - TZ=Europe/Madrid
      - USERID=1000
      - GROUPID=1000
      - SAMBA_USERS=wisrovi;wyoloservice
    command: >
      -u "wisrovi;wyoloservice" -s "shared;/data;yes;no;yes;all"
    ports:
      - "23447:445/tcp"
    networks:
      - nfs_network
    env_file:
      - control_host.env

  db_samba:
    image: dperson/samba
    restart: always
    volumes:
      - ${FOLDER_SHARED}/wyoloservice_data/api_database:/data
    environment:
      - TZ=Europe/Madrid
      - USERID=1000
      - GROUPID=1000
      - SAMBA_USERS=wisrovi;wyoloservice
    command: >
      -u "wisrovi;wyoloservice" -s "shared;/data;yes;no;yes;all"
    ports:
      - "23448:445/tcp"
    networks:
      - nfs_network
    env_file:
      - control_host.env



networks:
  nfs_network:
    external: true
