version: "3.8"

services:
  dataset_filebrowser:
    image: hurlenko/filebrowser
    privileged: true
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    volumes:
      - ./datasets:/data
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      # - FB_PASSWORD=wyoloservice
      # - FB_USERNAME=wisrovi
      - FB_BASEURL=/datasets
      - VIRTUAL_HOST=wisrovi.com
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=wisrovi.com
      - LETSENCRYPT_EMAIL=wisrovi.rodriguez@gmail.com
    restart: always
    # ports:
    #   - "23443:8080"
    networks:
      - nfs_network

  dataset_samba:
    image: dperson/samba
    ports:
      - "23445:445/tcp"
    restart: always
    volumes:
      - ./datasets:/data
    environment:
      - TZ=Europe/Madrid
      - USERID=1000
      - GROUPID=1000
      - SAMBA_USERS=wisrovi;wyoloservice
    command: >
      -u "wisrovi;wyoloservice" -s "shared;/data;yes;no;yes;all"
    networks:
      - nfs_network

  config_samba:
    image: dperson/samba
    restart: always
    volumes:
      - ./config_versions:/data
    environment:
      - TZ=Europe/Madrid
      - USERID=1000
      - GROUPID=1000
      - SAMBA_USERS=wisrovi;wyoloservice
    command: >
      -u "wisrovi;wyoloservice" -s "shared;/data;yes;no;yes;all"
    ports:
      - "23447:445/tcp"
    networks:
      - nfs_network

  db_samba:
    image: dperson/samba
    restart: always
    volumes:
      - ./api_database:/data
    environment:
      - TZ=Europe/Madrid
      - USERID=1000
      - GROUPID=1000
      - SAMBA_USERS=wisrovi;wyoloservice
    command: >
      -u "wisrovi;wyoloservice" -s "shared;/data;yes;no;yes;all"
    ports:
      - "23448:445/tcp"
    networks:
      - nfs_network



networks:
  nfs_network:
    external: true