content: "Este es un experimento de clasificación de imágenes."
model: "yolov8n-cls.pt"
type: "yolo"
train:
  batch: 32
  data: /datasets/clasificacion/colorball.v8i.multiclass/
  epochs: 1
  imgsz: 640
val:
  conf: 0.01
test:
  conf: 0.01
sweeper:
  version: 1.0
  direction: maximize
  study_name: "colorball"
  storage: null
  sampler: "TPESampler"
  n_trials: 3
  params:
    train:
      imgsz: [ "choice", 416 ]
      lr0: [ "loguniform", 1e-5, 1e-2 ]
extras:
  gpu:
    id: 0
    limit: 0.95
