defaults:
- override hydra/sweeper: optuna
content: "Este es un experimento de clasificación de imágenes."
model: "yolov8n.pt"
type: "yolo"
train:
  batch: 50
  data: /datasets/deteccion/Deteksi komponen elektronik.v1i.yolov8/data.yaml
  epochs: 1
  imgsz: 640
# val:
#   batch: 32
#   conf: 0.01
# test:
#   conf: 0.01
sweeper:
  version: 1
  direction: maximize
  study_name: "komponen_elektronik"
  storage: null
  sampler: "TPESampler"
  n_trials: 1
  params:
    train:
      imgsz: [ "choice", 416, 640 ]
      lr0: [ "loguniform", 1e-5, 1e-2 ]
extras:
  gpu:
    id: 0
    limit: 0.95
