events {}

http {
    # Configuración para HTTP (puerto 80)
    server {
        listen 80;
        server_name www.wyoloservice.com;

        # Redirigir tráfico HTTP a HTTPS
        location / {
            return 301 https://$host$request_uri;
        }
    }

    # Configuración para HTTPS (puerto 443)
    server {
        listen 443 ssl;
        server_name www.wyoloservice.com;

        # Rutas de los certificados SSL
        ssl_certificate /etc/nginx/certs/www.wyoloservice.com/fullchain.pem;
        ssl_certificate_key /etc/nginx/certs/www.wyoloservice.com/privkey.pem;

        # Configuraciones de seguridad SSL
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers 'TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384';
        ssl_prefer_server_ciphers on;

        # Configuración de las ubicaciones (rutas de tu API y servicios)
        location /api/ {
            proxy_pass http://api_user:8000/docs;
            proxy_set_header Host $host;
            rewrite ^/api(/.*)$ $1 break;
        }

        location /mlflow/ {
            proxy_pass http://mlflow:5000/;
            proxy_set_header Host $host;
            rewrite ^/mlflow(/.*)$ $1 break;
        }

        location /datasets/ {
            proxy_pass http://dataset_filebrowser:8080/;
            proxy_set_header Host $host;
            rewrite ^/datasets(/.*)$ $1 break;
        }

        location /redis_admin/ {
            proxy_pass http://redis_commander:8081/;
            proxy_set_header Host $host;
            rewrite ^/redis-admin(/.*)$ $1 break;
        }

        location /redis/ {
            proxy_pass http://redis:6379/;
            proxy_set_header Host $host;
            rewrite ^/redis(/.*)$ $1 break;
        }

        location /postgres/ {
            proxy_pass http://postgres:5432/;
            proxy_set_header Host $host;
            rewrite ^/postgres(/.*)$ $1 break;
        }

        location /minio/ {
            proxy_pass http://mlflow-minio:9001/;
            proxy_set_header Host $host;
            rewrite ^/minio(/.*)$ $1 break;
        }
    }
}
