version: "3.8"

# Define reusable GPU resource constraints
x-resources: &resources_gpu
  # la shm_size es calculada de acuerdo al 80% de la memoria RAM como maximo
  # es importante que el ordenador a entrenar tenga al menos lo mismo de swap que de RAM
  shm_size: "24g"  
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "3"
  environment:
    - NVIDIA_VISIBLE_DEVICES=0
    - NVIDIA_DRIVER_CAPABILITIES=compute,utility
  deploy:
    resources:
      limits:
        cpus: "7.0"
        memory: 24g
      reservations:
        devices:
          - driver: nvidia
            device_ids: ["0"]
            capabilities: [gpu]

services:
  worker:
    <<: *resources_gpu
    image: wisrovi/wyoloservice_worker
    env_file:
      - control_host.env
      - user.env
    restart: always
    privileged: true
    hostname: ${USER}
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    # command: tail -f /dev/null
    labels:
      - "autoheal=true"
      - "com.centurylinklabs.watchtower.enable=true" # Habilita Watchtower para este contenedor
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 20s
      timeout: 2s
      retries: 1
      start_period: 20s

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    environment:
      - WATCHTOWER_LABEL_ENABLE=true # Habilita el control por etiquetas
      - WATCHTOWER_SCHEDULE="0 0 0,2,4,6,8,10,12,14,16,18,20,22 * * *" # todos los segundos, minutos, dias, semanas, meses, a las horas 0,2,...,22
      - WATCHTOWER_CLEANUP=true # Elimina imágenes antiguas después de actualizar
    ports:
      - 8080:8080
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  autoheal:
    environment:
      - AUTOHEAL_INTERVAL=10
      - CURL_TIMEOUT=30
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    image: willfarrell/autoheal
    restart: always

