FROM ultralytics/ultralytics:8.3.86


USER root


# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1


RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get -y install net-tools
RUN apt-get -y install git
RUN apt install iputils-ping -y

RUN apt-get update && \
    apt-get install -y libgl1-mesa-glx
RUN apt-get install ffmpeg libsm6 libxext6  -y
RUN apt-get update && apt-get install ffmpeg libsm6 libxext6  -y


# Actualizar e instalar dependencias (incluyendo cifs-utils)
RUN apt-get update && apt-get install -y \
    make \
    cifs-utils \
    && rm -rf /var/lib/apt/lists/*

# ZSH
RUN apt-get update && apt-get install -y zsh
RUN apt-get install -y wget
# Uses "robbyrussell" theme (original Oh My Zsh theme), with no plugins
RUN sh -c "$(wget -O- https://github.com/deluan/zsh-in-docker/releases/download/v1.1.5/zsh-in-docker.sh)" -- \
    -t aussiegeek
# customizations
RUN apt-get install figlet -y
RUN echo "alias ll='ls -l'" >> ~/.zshrc


# Crear directorios de montaje
RUN mkdir -p /config_versions \
    && mkdir -p /database \
    && mkdir -p /datasets

RUN chmod -R 777 /config_versions \
    && chmod -R 777 /database \
    && chmod -R 777 /datasets    


# Limpiar caché y archivos temporales
RUN rm -rf /var/cache/apk/*
RUN rm -rf /tmp/*
RUN apt-get clean

# Copiar el script para montar las unidades CIFS
WORKDIR /usr/local/bin/
COPY mount-cifs.sh .
RUN chmod +x /usr/local/bin/mount-cifs.sh

# Configurar el entorno de trabajo
WORKDIR /app

# Instalar dependencias
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar wait-for-it.sh al contenedor
# COPY wait-for-it.sh /usr/local/bin/wait-for-it.sh
# RUN chmod +x /usr/local/bin/wait-for-it.sh


# Copiar el código fuente
WORKDIR /lib/wyoloservice
COPY lib .
RUN pip install -e .

WORKDIR /app/worker/
COPY worker/ .

WORKDIR /app/
COPY config.yaml .

# Exponer el puerto de FastAPI
EXPOSE 8000




WORKDIR /app/worker/

# # Initialize a Git repository
# RUN git init -q

# # Configure Git with your details
# RUN git config --local user.email "you@example.com"
# RUN git config --local user.name "Your Name"

# # Initialize DVCLive in your project
# RUN dvc init -q

# # Commit the DVCLive setup to your Git repository
# RUN git commit -m "DVC init"




RUN echo "figlet wyoloservice" >> ~/.zshrc
RUN echo "figlet wyoloservice" >> ~/.bashrc

RUN echo "sh -c /usr/local/bin/mount-cifs.sh" >> ~/.zshrc
RUN echo "sh -c /usr/local/bin/mount-cifs.sh" >> ~/.bashrc



RUN echo "alias train_service='python'" >> ~/.zshrc
RUN echo "alias train_service='python'" >> ~/.bashrc


# Create the train_service script
RUN echo '#!/bin/sh\nexec python "$@"' > /usr/local/bin/train_service && chmod +x /usr/local/bin/train_service



CMD ["sh", "-c", "/usr/local/bin/mount-cifs.sh && train_service worker.py"]