# https://fastapi.tiangolo.com/deployment/docker/#create-the-fastapi-code

FROM python:3.10.16-alpine3.20

USER root

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1


# Configurar el entorno de trabajo
WORKDIR /code

# Instalar dependencias
COPY api/requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

WORKDIR /code/app
COPY ./api /code/app
COPY ./lib/train_yolo/database.py /code/app
COPY config.yaml /code/app

WORKDIR /code/

CMD ["fastapi", "run", "app/main.py", "--proxy-headers", "--port", "8000", "--workers", "8"]
#CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]
