version: "3.8"


services:
  # api
  api_user:
    image: wisrovi/wyoloservice:api
    restart: always
    ports:
      - "23450:8000"
    volumes:
      - ./config_versions:/config_versions
      - ./api_database:/database
    networks:
      - nfs_network

  # environment
  redis:
    image: redis:latest
    restart: always
    ports:
      - "23438:6379"
    networks:
      - nfs_network

  redis_commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=wisrovi
      - HTTP_PASSWORD=wyoloservice
    # ports:
    #   - "23439:8081"
    depends_on:
      - redis
    networks:
      - nfs_network

  mlflow_minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    restart: always
    environment:
      - MINIO_ROOT_USER=wisrovi
      - MINIO_ROOT_PASSWORD=wyoloservice
    ports:
      - "23444:9000"
      - "23442:9001" # web admin
    volumes:
      - ./mlflow_minio:/data
    networks:
      - nfs_network

  mlflow:
    image: wisrovi/wyoloservice:mlflow
    restart: always
    environment:
      # db
      - MLFLOW_BACKEND_STORE_URI=postgresql+psycopg2://postgres:postgres@postgres:5432/wyoloservice # Conexión a PostgreSQL
      # minio
      - MLFLOW_S3_ENDPOINT_URL=http://mlflow-minio:9000 # URL del servidor MinIO
      - AWS_ACCESS_KEY_ID=wisrovi # Credenciales de MinIO
      - AWS_SECRET_ACCESS_KEY=wyoloservice # Credenciales de MinIO
      #mlflow
      - MLFLOW_TRACKING_URI=http://mlflow:5000 # URI de seguimiento de MLflow
      - MLFLOW_ARTIFACT_URI=s3://mlflow-artifacts/ # Bucket en MinIO donde se almacenarán los artefactos
    command:
      [
        "mlflow",
        "server",
        "--host",
        "0.0.0.0",
        "--port",
        "5000",
        "--backend-store-uri",
        "postgresql+psycopg2://postgres:postgres@postgres:5432/wyoloservice",
        "--default-artifact-root",
        "s3://mlflow-artifacts/",
      ]
    # ports:
    #   - "23435:5000"
    networks:
      - nfs_network

  postgres:
    image: postgres:13.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=wyoloservice
    volumes:
      - /media/training/Train_service_an/postgres:/var/lib/postgresql/data
    ports:
      - "23436:5432"
    restart: always
    networks:
      - nfs_network

    # General:
    #     name: postgres
    # conection:
    #     host name/address: postgres
    #     port: 5432
    #     username: postgres
    #     password: postgres


networks:
  nfs_network:
    external: true

volumes:
  pgadmin-data:
