version: '3.8'

services:
  dataset_filebrowser:
    image: hurlenko/filebrowser
    privileged: true
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    volumes:
      - ${FOLDER_SHARED}/datasets:/data
    env_file:
      - control_host.env
    environment:
      - FB_BASEURL=/datasets
    restart: always
    ports:
      - "23443:8080"
    networks:
      - nfs_network

  combined_samba:
    image: dperson/samba
    ports:
      - "23445:445/tcp" # Puerto único para el servicio combinado
    restart: always
    env_file:
      - control_host.env
    volumes:
      - ${FOLDER_SHARED}/datasets:/data/datasets
      - ${FOLDER_SHARED}/config_versions:/data/config_versions
      - ${FOLDER_SHARED}/api_database:/data/api_database
    command: >
      -u "${CIFS_USER};${CIFS_PASS}"
      -s "datasets;/data/datasets;yes;no;yes;all"
      -s "config_versions;/data/config_versions;yes;no;yes;all"
      -s "api_database;/data/api_database;yes;no;yes;all"
    networks:
      - nfs_network

networks:
  nfs_network:
    driver: bridge

# mkdir -p /home/wrodriguez/Descargas/PT/{datasets,config_versions,api_database}
